import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import LandingPage from "../components/LandingPage";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Louis Qian | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <LandingPage />

      <Skills />
    </div>
  );
}
