/*
Auto-generated by: https://github.com/pmndrs/gltfjsx, modified by Louis Qian
Command: npx gltfjsx@6.1.4 public/push.gltf --shadows --transform --types
*/

import * as THREE from "three";
import React, { useMemo, useState } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
  useCursor,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Button_Top: THREE.Mesh;
    Button_Base: THREE.Mesh;
    Sign_String: THREE.Mesh;
    Sign_Text: THREE.Mesh;
    Sign_Sheet: THREE.Mesh;
    Sign_board: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Ellipse_1: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Rectangle_4: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cylinder_3: THREE.Mesh;
    Cylinder_2_1: THREE.Mesh;
    Cylinder_4: THREE.Mesh;
    Rectangle_3: THREE.Mesh;
    Rectangle_3_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Ellipse_2: THREE.Mesh;
    Ellipse: THREE.Mesh;
    Cube_6: THREE.Mesh;
    Cube_5: THREE.Mesh;
    Cube_6_1: THREE.Mesh;
    Cube_4: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder_11: THREE.Mesh;
    Cylinder_10: THREE.Mesh;
    Cylinder_11_1: THREE.Mesh;
    Cylinder_9: THREE.Mesh;
    Cylinder_12: THREE.Mesh;
    Cube_17_1: THREE.Mesh;
    Cube_16_1: THREE.Mesh;
    Cube_15_1: THREE.Mesh;
    Cube_18_1: THREE.Mesh;
    Rectangle_6: THREE.Mesh;
    Cylinder_15: THREE.Mesh;
    Cylinder_13: THREE.Mesh;
    Cube_21_1: THREE.Mesh;
    Cube_19: THREE.Mesh;
    Cube_23_1: THREE.Mesh;
    Cube_14: THREE.Mesh;
    Cube_22_1: THREE.Mesh;
    Cube_20_1: THREE.Mesh;
    Rectangle_2_1: THREE.Mesh;
    Cylinder_14: THREE.Mesh;
    Cylinder_7: THREE.Mesh;
    Rectangle_9: THREE.Mesh;
    Cube_21: THREE.Mesh;
    Cube_18: THREE.Mesh;
    Cube_17: THREE.Mesh;
    Cube_16: THREE.Mesh;
    Cube_20: THREE.Mesh;
    Cube_15: THREE.Mesh;
    Cube_25: THREE.Mesh;
    Cube_24: THREE.Mesh;
    Cube_26: THREE.Mesh;
    Cube_23: THREE.Mesh;
    Cube_22: THREE.Mesh;
    Cylinder_6: THREE.Mesh;
    Cube_13: THREE.Mesh;
    Cube_13_1: THREE.Mesh;
    Cube_7_1: THREE.Mesh;
    Rectangle_8: THREE.Mesh;
    Cylinder_5_1: THREE.Mesh;
    Cube_12: THREE.Mesh;
    Cube_11: THREE.Mesh;
    Cube_6_2: THREE.Mesh;
    Rectangle_7: THREE.Mesh;
    Cylinder_9_1: THREE.Mesh;
    Cylinder_10_1: THREE.Mesh;
    Cylinder_8: THREE.Mesh;
    Cylinder_7_1: THREE.Mesh;
    Cube_5_1: THREE.Mesh;
    Rectangle_6_1: THREE.Mesh;
    Cylinder_4_3: THREE.Mesh;
    Cube_10: THREE.Mesh;
    Cube_4_1: THREE.Mesh;
    Rectangle_5_1: THREE.Mesh;
    Cylinder_3_2: THREE.Mesh;
    Cube_9_1: THREE.Mesh;
    Cube_3_3: THREE.Mesh;
    Rectangle_4_4: THREE.Mesh;
    Cylinder_2_3: THREE.Mesh;
    Cube_8_1: THREE.Mesh;
    Cube_2_3: THREE.Mesh;
    Rectangle_3_4: THREE.Mesh;
    Cube_7_2: THREE.Mesh;
    Cube_6_3: THREE.Mesh;
    Cube_5_2: THREE.Mesh;
    Cube_4_2: THREE.Mesh;
    Cube_3_4: THREE.Mesh;
    Cube_7_3: THREE.Mesh;
    Cube_6_4: THREE.Mesh;
    Cube_5_3: THREE.Mesh;
    Cube_4_3: THREE.Mesh;
    Cube_3_5: THREE.Mesh;
    Cube_7_4: THREE.Mesh;
    Cube_6_5: THREE.Mesh;
    Cube_5_4: THREE.Mesh;
    Cube_4_4: THREE.Mesh;
    Cube_3_6: THREE.Mesh;
    Cube_7_5: THREE.Mesh;
    Cube_6_6: THREE.Mesh;
    Cube_5_5: THREE.Mesh;
    Cube_4_5: THREE.Mesh;
    Cube_3_7: THREE.Mesh;
    Cube_7_6: THREE.Mesh;
    Cube_6_7: THREE.Mesh;
    Cube_5_6: THREE.Mesh;
    Cube_4_6: THREE.Mesh;
    Cube_3_8: THREE.Mesh;
    Cube_9_2: THREE.Mesh;
    Cube_8_2: THREE.Mesh;
    Cube_7_7: THREE.Mesh;
    Cube_6_8: THREE.Mesh;
    Cube_5_7: THREE.Mesh;
    Cube_4_7: THREE.Mesh;
    Cube_3_9: THREE.Mesh;
    Cube_2_1: THREE.Mesh;
    Keyboard: THREE.Mesh;
    Rectangle_1: THREE.Mesh;
    Rectangle_2: THREE.Mesh;
    Rectangle_5: THREE.Mesh;
    Rectangle_3_2: THREE.Mesh;
    Cylinder_4_1: THREE.Mesh;
    Cylinder_3_1: THREE.Mesh;
    Cylinder_4_2: THREE.Mesh;
    Cylinder_2_2: THREE.Mesh;
    Rectangle_4_1: THREE.Mesh;
    Plane: THREE.Mesh;
    Rectangle_4_2: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Triangle: THREE.Mesh;
    Ellipse_3: THREE.Mesh;
    Laptop_1: THREE.Mesh;
    Rectangle_4_3: THREE.Mesh;
    Rectangle_3_3: THREE.Mesh;
    Screen_2: THREE.Mesh;
    Cube_7: THREE.Mesh;
    Screen_1: THREE.Mesh;
    Cube_8: THREE.Mesh;
    Cube_3_1: THREE.Mesh;
    Cube_3_2: THREE.Mesh;
    Cube_2_2: THREE.Mesh;
    Cube_9: THREE.Mesh;
    Cylinder_5: THREE.Mesh;
    Desk_Leg_RT: THREE.Mesh;
    Desk_Leg_LT: THREE.Mesh;
    Desk_Leg_RB: THREE.Mesh;
    Desk_Leg_LB: THREE.Mesh;
    Cube_3: THREE.Mesh;
    Desk_Top: THREE.Mesh;
    Wall_Left: THREE.Mesh;
    Wall_Bottom: THREE.Mesh;
    Wall_Right: THREE.Mesh;
    Rectangle: THREE.Mesh;
  };
  materials: {};
};

interface ModelProps {
  props?: JSX.IntrinsicElements["group"];
  setSocialOpen: React.Dispatch<React.SetStateAction<boolean>>;
}

export const RoomModel: React.FC<ModelProps> = ({ props, setSocialOpen }) => {
  const { nodes, materials } = useGLTF("/Room_Model.glb") as GLTFResult;
  const glassMaterial = useMemo(
    () =>
      new THREE.MeshPhysicalMaterial({
        transmission: 0.85,
        opacity: 1,
        transparent: true,
        ior: 1.5,
        thickness: 0.1,
        specularIntensity: 1,
        envMapIntensity: 1,
      }),
    []
  );
  const [hovered, setHovered] = useState(false);
  useCursor(hovered, "pointer");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[173.45, 40.97, 139.5]}>
          <group position={[0, 29.36, -1.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button_Top.geometry}
              material={nodes.Button_Top.material}
              position={[2.02, -0.19, 0.39]}
              rotation={[0, -Math.PI / 2, 0]}
              onPointerOver={() => setHovered(true)}
              onPointerOut={() => setHovered(false)}
              onUpdate={(self) => {
                if (hovered) {
                  self.position.z = 1;
                } else {
                  self.position.z = 0;
                }
              }}
              onClick={() => {
                // @ts-ignore
                nodes.Button_Top.material.emissive = new THREE.Color(0xff0000);
                setTimeout(() => {
                  // @ts-ignore
                  nodes.Button_Top.material.emissive = new THREE.Color(
                    0x000000
                  );
                }, 3000);
                setSocialOpen(true);
                setTimeout(() => {
                  setSocialOpen(false);
                }, 3000);
              }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button_Base.geometry}
              material={nodes.Button_Base.material}
              position={[5.98, 0, 0]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sign_String.geometry}
            material={nodes.Sign_String.material}
            position={[2.6, -0.1, -28.46]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sign_Text.geometry}
            material={nodes.Sign_Text.material}
            position={[-2.45, -24.03, 0.3]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sign_Sheet.geometry}
            material={nodes.Sign_Sheet.material}
            position={[-1.45, -23.63, 0.08]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sign_board.geometry}
            material={nodes.Sign_board.material}
            position={[3.55, -23.97, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group position={[2.73, 286.06, -0.34]}>
          <spotLight
            intensity={0.63}
            angle={0.72}
            penumbra={0.4}
            decay={2}
            distance={1562}
            color="#ff9c00"
            position={[-0.6, -2.77, 2.58]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={nodes.Sphere.material}
            position={[-1.73, -6.7, 1.34]}
            rotation={[2.07, 0.17, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={nodes.Cylinder.material}
            position={[-1.5, 8.95, 1.86]}
            rotation={[Math.PI, 0, -Math.PI]}
          />
        </group>
        <group position={[74.89, -103.55, 56.52]} rotation={[0, 0.56, 0]}>
          <group position={[0, 0, 1.5]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_1.geometry}
              material={nodes.Ellipse_1.material}
              position={[-7.01, 0.01, -0.02]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_1.geometry}
              material={nodes.Cylinder_1.material}
              rotation={[Math.PI, 0, Math.PI / 2]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_4.geometry}
            material={nodes.Rectangle_4.material}
            position={[8.86, 11.9, -4.52]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[7.37, 1.21, -12.03]}
            rotation={[Math.PI, -1.57, Math.PI / 2]}
            scale={[1, 1, 1.11]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={nodes.Cube_1.material}
            position={[8.87, 1.17, -1.5]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[135, -168.63, 136.78]}>
          <group position={[-0.63, 16.37, 0.27]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3.geometry}
              material={nodes.Cylinder_3.material}
              position={[0, 0, 11.04]}
              rotation={[Math.PI, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2_1.geometry}
              material={nodes.Cylinder_2_1.material}
              position={[0, 0, -0.1]}
              rotation={[Math.PI, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_4.geometry}
              material={nodes.Cylinder_4.material}
              position={[0, 0, -11.04]}
              rotation={[Math.PI, 0, -Math.PI]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_3.geometry}
            material={nodes.Rectangle_3.material}
            position={[-24.54, -21.37, 0.22]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_3_1.geometry}
            material={nodes.Rectangle_3_1.material}
            position={[-25.19, -5.87, 0.22]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={nodes.Cube_2.material}
            position={[0, -6.48, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[-60, -198.79, -10]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse_2.geometry}
            material={nodes.Ellipse_2.material}
            position={[-2.16, 0.08, 0.97]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse.geometry}
            material={nodes.Ellipse.material}
            position={[0, -1.08, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[-2.49, -161.7, -7.01]}>
          <group position={[-0.49, -4.7, 0.4]} scale={[1, 1.21, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_6.geometry}
              material={nodes.Cube_6.material}
              position={[0.19, 0, 21.23]}
              rotation={[-1.67, 0, Math.PI / 2]}
              scale={[1, 1, 7.38]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_5.geometry}
              material={nodes.Cube_5.material}
              position={[21.5, 0, -0.08]}
              rotation={[-Math.PI / 2, -0.12, -Math.PI]}
              scale={[1, 1, 7.38]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_6_1.geometry}
              material={nodes.Cube_6_1.material}
              position={[0.19, 0, -21.39]}
              rotation={[-1.48, 0, Math.PI / 2]}
              scale={[1, 1, 7.38]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_4.geometry}
              material={nodes.Cube_4.material}
              position={[-21.12, 0, -0.08]}
              rotation={[-Math.PI / 2, 0.13, -Math.PI]}
              scale={[1, 1, 7.38]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={nodes.Cylinder_2.material}
            position={[0, 35.86, 0]}
            rotation={[Math.PI, 0, -Math.PI]}
          />
        </group>
        <group position={[-61.19, -160.75, -137.02]}>
          <group position={[13.2, 55.12, -8.57]} rotation={[0.16, 0, 0]}>
            <group position={[-37.21, 0, -0.2]}>
              <group position={[7.89, 0.5, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_11.geometry}
                  material={nodes.Cylinder_11.material}
                  position={[0, 1, 0.68]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_10.geometry}
                  material={nodes.Cylinder_10.material}
                  position={[3.92, 1, 0.68]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_11_1.geometry}
                  material={nodes.Cylinder_11_1.material}
                  position={[0, 1, 5.12]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_9.geometry}
                  material={nodes.Cylinder_9.material}
                  position={[3.92, 1, 5.12]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_12.geometry}
                  material={nodes.Cylinder_12.material}
                  position={[-4.53, -1, -4.42]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_17_1.geometry}
                  material={nodes.Cube_17_1.material}
                  position={[-4.45, -1, -0.58]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_16_1.geometry}
                  material={nodes.Cube_16_1.material}
                  position={[-0.9, -1, -4.46]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_15_1.geometry}
                  material={nodes.Cube_15_1.material}
                  position={[3.94, -1, -4.46]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_18_1.geometry}
                  material={nodes.Cube_18_1.material}
                  position={[-4.46, -1, 4.24]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_6.geometry}
                  material={nodes.Rectangle_6.material}
                  position={[0, -2, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[-7.89, -0.5, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_15.geometry}
                  material={nodes.Cylinder_15.material}
                  position={[0.28, 0, 4.52]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_13.geometry}
                  material={nodes.Cylinder_13.material}
                  position={[-4.88, 0, -4.45]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_21_1.geometry}
                  material={nodes.Cube_21_1.material}
                  position={[3.89, 0, -4.3]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_19.geometry}
                  material={nodes.Cube_19.material}
                  position={[3.89, 0, 4.54]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_23_1.geometry}
                  material={nodes.Cube_23_1.material}
                  position={[-3.6, 0, 0.02]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_14.geometry}
                  material={nodes.Cube_14.material}
                  position={[3.1, 0, 0.03]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_22_1.geometry}
                  material={nodes.Cube_22_1.material}
                  position={[-0.75, 0, -4.2]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_20_1.geometry}
                  material={nodes.Cube_20_1.material}
                  position={[-3.56, 0, 4.53]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2_1.geometry}
                  material={nodes.Rectangle_2_1.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_14.geometry}
                material={nodes.Cylinder_14.material}
                position={[-18.16, -0.5, -4.33]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <group position={[-9.16, -0.5, 0.2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_7.geometry}
                material={nodes.Cylinder_7.material}
                position={[-10.93, 0, -0.22]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_9.geometry}
                material={nodes.Rectangle_9.material}
                position={[-0.8, -1, -0.52]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_21.geometry}
                material={nodes.Cube_21.material}
                position={[10.24, 0, 2.39]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_18.geometry}
                material={nodes.Cube_18.material}
                position={[10.24, 0, 5.73]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_17.geometry}
                material={nodes.Cube_17.material}
                position={[6.01, 0, 5.73]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_16.geometry}
                material={nodes.Cube_16.material}
                position={[1.72, 0, 5.73]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_20.geometry}
                material={nodes.Cube_20.material}
                position={[-7.16, 0, 5.73]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_15.geometry}
                material={nodes.Cube_15.material}
                position={[-2.76, 0, 5.73]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_25.geometry}
                material={nodes.Cube_25.material}
                position={[10.14, 0, -6.32]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_24.geometry}
                material={nodes.Cube_24.material}
                position={[4.38, 0, -6.32]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_26.geometry}
                material={nodes.Cube_26.material}
                position={[-7.07, 0, -6.32]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_23.geometry}
                material={nodes.Cube_23.material}
                position={[-1.99, 0, -6.32]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1.17, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_22.geometry}
                material={nodes.Cube_22.material}
                position={[-11.24, 0, 5.31]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[1, 1.17, 1]}
              />
            </group>
            <group position={[25.89, -0.5, -0.2]}>
              <group position={[19.22, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_6.geometry}
                  material={nodes.Cylinder_6.material}
                  position={[-0.03, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_13.geometry}
                  material={nodes.Cube_13.material}
                  position={[-0.03, 0, -1.2]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_13_1.geometry}
                  material={nodes.Cube_13_1.material}
                  position={[-0.03, 0, 2.47]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_1.geometry}
                  material={nodes.Cube_7_1.material}
                  position={[-0.05, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_8.geometry}
                  material={nodes.Rectangle_8.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[12.66, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_5_1.geometry}
                  material={nodes.Cylinder_5_1.material}
                  position={[-0.04, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_12.geometry}
                  material={nodes.Cube_12.material}
                  position={[-0.16, 0, -1.2]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_11.geometry}
                  material={nodes.Cube_11.material}
                  position={[-0.16, 0, 2.47]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_2.geometry}
                  material={nodes.Cube_6_2.material}
                  position={[-0.05, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_7.geometry}
                  material={nodes.Rectangle_7.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[3.73, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_9_1.geometry}
                  material={nodes.Cylinder_9_1.material}
                  position={[2.13, 0, 5.02]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_10_1.geometry}
                  material={nodes.Cylinder_10_1.material}
                  position={[-2.19, 0, -0.32]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_8.geometry}
                  material={nodes.Cylinder_8.material}
                  position={[2.13, 0, -0.32]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_7_1.geometry}
                  material={nodes.Cylinder_7_1.material}
                  position={[2.13, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_1.geometry}
                  material={nodes.Cube_5_1.material}
                  position={[-1.78, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_6_1.geometry}
                  material={nodes.Rectangle_6_1.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[-5.33, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_4_3.geometry}
                  material={nodes.Cylinder_4_3.material}
                  position={[0, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_10.geometry}
                  material={nodes.Cube_10.material}
                  position={[-0.01, 0, 1.37]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_1.geometry}
                  material={nodes.Cube_4_1.material}
                  position={[0, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_5_1.geometry}
                  material={nodes.Rectangle_5_1.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[-12.31, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_3_2.geometry}
                  material={nodes.Cylinder_3_2.material}
                  position={[-0.08, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_9_1.geometry}
                  material={nodes.Cube_9_1.material}
                  position={[-0.08, 0, 1.37]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_3.geometry}
                  material={nodes.Cube_3_3.material}
                  position={[-0.01, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_4_4.geometry}
                  material={nodes.Rectangle_4_4.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
              <group position={[-19.22, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_2_3.geometry}
                  material={nodes.Cylinder_2_3.material}
                  position={[-0.1, 0, -5.88]}
                  rotation={[0, -Math.PI / 2, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_8_1.geometry}
                  material={nodes.Cube_8_1.material}
                  position={[0.08, 0, 1.37]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_2_3.geometry}
                  material={nodes.Cube_2_3.material}
                  position={[0.08, 0, 6.12]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1, 1.17, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3_4.geometry}
                  material={nodes.Rectangle_3_4.material}
                  position={[0, -1, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
              </group>
            </group>
          </group>
          <group position={[0, 45.13, 4.54]} scale={[1, 1, 0.83]}>
            <group position={[7.27, 0, 8.36]}>
              <group position={[67.55, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_2.geometry}
                  material={nodes.Cube_7_2.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_3.geometry}
                  material={nodes.Cube_6_3.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_2.geometry}
                  material={nodes.Cube_5_2.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_2.geometry}
                  material={nodes.Cube_4_2.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_4.geometry}
                  material={nodes.Cube_3_4.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <group position={[36.29, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_3.geometry}
                  material={nodes.Cube_7_3.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_4.geometry}
                  material={nodes.Cube_6_4.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_3.geometry}
                  material={nodes.Cube_5_3.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_3.geometry}
                  material={nodes.Cube_4_3.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_5.geometry}
                  material={nodes.Cube_3_5.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <group position={[4.46, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_4.geometry}
                  material={nodes.Cube_7_4.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_5.geometry}
                  material={nodes.Cube_6_5.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_4.geometry}
                  material={nodes.Cube_5_4.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_4.geometry}
                  material={nodes.Cube_4_4.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_6.geometry}
                  material={nodes.Cube_3_6.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <group position={[-27.06, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_5.geometry}
                  material={nodes.Cube_7_5.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_6.geometry}
                  material={nodes.Cube_6_6.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_5.geometry}
                  material={nodes.Cube_5_5.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_5.geometry}
                  material={nodes.Cube_4_5.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_7.geometry}
                  material={nodes.Cube_3_7.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <group position={[-58.24, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_6.geometry}
                  material={nodes.Cube_7_6.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_7.geometry}
                  material={nodes.Cube_6_7.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_6.geometry}
                  material={nodes.Cube_5_6.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_6.geometry}
                  material={nodes.Cube_4_6.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_8.geometry}
                  material={nodes.Cube_3_8.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <group position={[89.6, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_9_2.geometry}
                  material={nodes.Cube_9_2.material}
                  position={[3.01, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_8_2.geometry}
                  material={nodes.Cube_8_2.material}
                  position={[-3.01, 0, 0]}
                />
              </group>
              <group position={[-89.6, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_7_7.geometry}
                  material={nodes.Cube_7_7.material}
                  position={[11.72, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_6_8.geometry}
                  material={nodes.Cube_6_8.material}
                  position={[6.54, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5_7.geometry}
                  material={nodes.Cube_5_7.material}
                  position={[1.33, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4_7.geometry}
                  material={nodes.Cube_4_7.material}
                  position={[-6.85, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3_9.geometry}
                  material={nodes.Cube_3_9.material}
                  position={[-12.02, 0, 0]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_2_1.geometry}
                material={nodes.Cube_2_1.material}
                position={[-109.49, 0, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Keyboard.geometry}
              material={nodes.Keyboard.material}
              position={[0, -5.68, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[1, 1, 0.55]}
            />
          </group>
          <group position={[-0.26, 44.74, 1.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_1.geometry}
              material={nodes.Rectangle_1.material}
              position={[0.26, -7.99, 24.52]}
              rotation={[0, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2.geometry}
              material={nodes.Rectangle_2.material}
              position={[114.66, 13.2, -0.05]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_5.geometry}
              material={nodes.Rectangle_5.material}
              position={[-107.2, 13.2, -0.05]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_3_2.geometry}
              material={nodes.Rectangle_3_2.material}
              position={[111.8, 13.41, -13.87]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[1, 1, 1.71]}
            />
          </group>
          <group position={[-0.67, -5.69, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_4_1.geometry}
              material={nodes.Cylinder_4_1.material}
              position={[99.31, 0.24, 23.07]}
              rotation={[2.98, 0, -Math.PI]}
              scale={[1, 0.59, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3_1.geometry}
              material={nodes.Cylinder_3_1.material}
              position={[-99.31, 0.24, 23.07]}
              rotation={[2.98, 0, -Math.PI]}
              scale={[1, 0.59, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_4_2.geometry}
              material={nodes.Cylinder_4_2.material}
              position={[99.31, -0.2, -23.51]}
              rotation={[-2.99, 0, -Math.PI]}
              scale={[1, 0.59, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2_2.geometry}
              material={nodes.Cylinder_2_2.material}
              position={[-99.31, -0.2, -23.51]}
              rotation={[-2.99, 0, -Math.PI]}
              scale={[1, 0.59, 1]}
            />
          </group>
        </group>
        <group position={[-22.96, -40.85, -173.67]}>
          <group position={[-68.96, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4_1.geometry}
              material={glassMaterial}
              position={[0.5, -0.5, 0.93]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane.geometry}
              material={nodes.Plane.material}
              position={[0, 0, -3.33]}
            />
          </group>
          <group position={[68.96, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4_2.geometry}
              material={glassMaterial}
              position={[0.5, -0.5, 0.93]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_1.geometry}
              material={nodes.Plane_1.material}
              position={[0, 0, -3.33]}
            />
          </group>
        </group>
        <group position={[113, -156.66, -39.74]} scale={[1.01, 0.92, 1]}>
          <group position={[30.81, 50.99, 46.24]} scale={[0.99, 1.08, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Triangle.geometry}
              material={nodes.Triangle.material}
              position={[-5, 1.55, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_3.geometry}
              material={nodes.Ellipse_3.material}
              position={[1.5, 1.55, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Laptop_1.geometry}
              material={nodes.Laptop_1.material}
              position={[0, -0.55, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[2.09, 0.67, 0.11]}
            />
          </group>
          <group position={[-21.33, 52.66, -0.26]} scale={[0.99, 1.08, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4_3.geometry}
              material={nodes.Rectangle_4_3.material}
              position={[10.46, -2, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_3_3.geometry}
              material={nodes.Rectangle_3_3.material}
              position={[-20.96, -2, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
          </group>
          <group position={[30.76, 98.11, 0.73]} scale={[0.99, 1.08, 1]}>
            <group
              position={[-1.62, 11.83, 55.14]}
              rotation={[-Math.PI, 0.23, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen_2.geometry}
                material={nodes.Screen_2.material}
                position={[-3.72, -0.02, -0.05]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_7.geometry}
                material={nodes.Cube_7.material}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <group position={[-1.43, 11.83, -55.14]} rotation={[0, 0.23, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen_1.geometry}
                material={nodes.Screen_1.material}
                position={[-3.72, -0.02, -0.05]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_8.geometry}
                material={nodes.Cube_8.material}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <group position={[14.03, 9.43, -26.28]} rotation={[-Math.PI, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_3_1.geometry}
                material={nodes.Cube_3_1.material}
                position={[0, 0, 19.77]}
                rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_3_2.geometry}
                material={nodes.Cube_3_2.material}
                position={[8.89, 0, -9.03]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <group position={[14.03, 9.43, 23.66]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_2_2.geometry}
                material={nodes.Cube_2_2.material}
                position={[0, 0, 19.77]}
                rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_9.geometry}
                material={nodes.Cube_9.material}
                position={[8.89, 0, -9.03]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <spotLight
              intensity={0.35}
              angle={1.4}
              penumbra={0.2}
              decay={2}
              distance={973}
              position={[-0.57, 5.05, 53.21]}
              rotation={[0, -0.23, -Math.PI / 2]}
            />
            <spotLight
              intensity={0.35}
              angle={1.4}
              penumbra={0.2}
              decay={2}
              distance={973}
              position={[-0.57, 5.05, -56.26]}
              rotation={[0, 0.24, -Math.PI / 2]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_5.geometry}
              material={nodes.Cylinder_5.material}
              position={[22.05, -14.31, -0.99]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
          </group>
          <group position={[0.24, -3.93, 0.7]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Desk_Leg_RT.geometry}
              material={nodes.Desk_Leg_RT.material}
              position={[45.12, 0, 110.24]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Desk_Leg_LT.geometry}
              material={nodes.Desk_Leg_LT.material}
              position={[45.12, 0, -110.24]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Desk_Leg_RB.geometry}
              material={nodes.Desk_Leg_RB.material}
              position={[-45.12, 0, 110.24]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Desk_Leg_LB.geometry}
              material={nodes.Desk_Leg_LB.material}
              position={[-45.12, 0, -110.24]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={nodes.Cube_3.material}
            position={[45.39, 52.91, -102.87]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[0.99, 1, 1.08]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Top.geometry}
            material={nodes.Desk_Top.material}
            position={[0, 35.93, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[0, -46, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_Left.geometry}
            material={nodes.Wall_Left.material}
            position={[-91, 4.5, -150]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_Bottom.geometry}
            material={nodes.Wall_Bottom.material}
            position={[0, -154, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_Right.geometry}
            material={nodes.Wall_Right.material}
            position={[200, 1, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <PerspectiveCamera
          makeDefault={false}
          far={100000}
          near={70}
          fov={45}
          position={[-838.27, 182.78, 867.36]}
          rotation={[-0.24, -0.81, -0.18]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-1050.15, 154.39, 184.86]}
          rotation={[-0.92, -1.28, -0.9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle.geometry}
          material={nodes.Rectangle.material}
          position={[173, 44.5, -84]}
          rotation={[0, -Math.PI / 2, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/Room_Model.glb");
